FROM nvcr.io/nvidia/l4t-pytorch:r35.2.1-pth2.0-py3
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y ffmpeg

RUN pip install \
    colorlog==6.8.0 \
    pyyaml==5.3.1 \
    httpx==0.25.0 \
    pydantic==2.1.1 \
    fastapi==0.101.0 \
    pydantic==2.1.1 \
    websockets==10.4 \
    exceptiongroup==1.1.3 \
    anyio==4.0.0 \
    uvicorn==0.20.0 \
    python-multipart==0.0.6 \
    nltk==3.8.1 \
    numpy==1.24.4 \
    openai-whisper

WORKDIR /opt/inno/ijarvis
CMD /bin/bash